### ISSUE TITLE
Unable to zoom

### ISSUE THREAD

**Issue by leeniu** [cross-platform/icloud-for-linux#10]
**Issue:** 

I have a hidpi display and contents of the apps are too small for me. I need to ability to zoom in, similar to "ctrl" + "+" / "-" on standard web pages. 

**Info:**

Running snapd on Pop!_OS 19.10 on an AMD desktop pc with a BenQ 32'' display.

I'm not sure about what can be done from this repo since there is not much custom code in here, but because I do not understand snaps yet, I leave the judgement to the maintainer :).

Thanks for this package anyway.

**Comment by MarcusTomlinson** [comment]
Fixed in 0.5

**Comment by leeniu** [comment]
@MarcusTomlinson sry to necro this ticket. First up, thanks for the fix, I can confirm it's working. Is there a way to remember the zoom level? I have to zoom in again every time I re-open one of the apps.

**Comment by MarcusTomlinson** [comment]
> @MarcusTomlinson sry to necro this ticket. First up, thanks for the fix, I can confirm it's working. Is there a way to remember the zoom level? I have to zoom in again every time I re-open one of the apps.

Sure, I’ll look into it.

**Comment by bshaw** [comment]
+1
Some snaps are able to scale by adding the force-device-scale-factor flag to the Exec line in the launcher, for example:

```--force-device-scale-factor=2.0```

I've tried adding this to `/var/lib/snapd/desktop/applications/icloud-for-linux_calendar.desktop`, but no luck. I've not created any snaps, but will do some poking around and let you know if I find anything.
