### ISSUE TITLE
Fontconfig warning: FcPattern object weight does not accept value [x y)

### ISSUE THREAD

**Issue by slinkouswasalreadytaken** [cross-platform/icloud-for-linux#16]
Installed a while ago using snap on the latest version of Manjaro (linux57). It worked fine at first, but now it doesn't even open. Reinstalled, but still no luck. iCloud opens fine on chromium and firefox.

**Comment by MarcusTomlinson** [comment]
Could you try re-installing like this:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

If this still doesn't work, try `snap install icloud-for-linux --devmode` in place of the third step above.

If this does not work, please run `icloud-for-linux.notes` from the terminal and share the output here.

Thanks.

**Comment by slinkouswasalreadytaken** [comment]
Hmm, I did that, with the same problem...
```
[slinkous@MacBookAir ~]$ icloud-for-linux.notes
"/home/slinkous/notes" does not exist.
"/home/slinkous/iCloud Notes" does not exist.
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault (core dumped)
[slinkous@MacBookAir ~]$ 
```

**Comment by MarcusTomlinson** [comment]
@slinkouswasalreadytaken could you have a look at https://github.com/cross-platform/icloud-for-linux/issues/9, looks like the same issue you're having.

**Comment by MarcusTomlinson** [comment]
Duplicate of: https://github.com/cross-platform/icloud-for-linux/issues/17
