### ISSUE TITLE
Cannot Open on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ThanhhDatt** [cross-platform/icloud-for-linux#22]
Hi Macus
I've already install it on Ubuntu 20.04 LTS
But when i open, it appears with blank screen and disappear immediately
Did i miss anything??

**Comment by ThanhhDatt** [comment]
I did like this but nothing happen :< 

```bash
# Uninstall icloud-for-linux
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux

# Clear font cache
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
sudo fc-cache -f -v

# Re-install icloud-for-linux
snap install icloud-for-linux
```

**Comment by MarcusTomlinson** [comment]
Are you perhaps running this in a virtual machine?

**Comment by ThanhhDatt** [comment]
No Marcus, I dual boot Ubuntu and Windows

**Comment by ThanhhDatt** [comment]
Thanks Marcus, after reinstall Ubuntu, i can use it
It works perfectly but a little bit slowly when i first open it
But generally, it's nice
