### ISSUE TITLE
Can't attach files

### ISSUE THREAD

**Issue by LevBernstein** [cross-platform/icloud-for-linux#26]
Running ParrotOS 4.10 (based on Debian Buster). Whenever I press the "attach" button, nothing happens in the GUI; the window to some kind of file manager does not open. My terminal outputs the following:

```
QtWebEngine: component error: file:///snap/icloud-for-linux/166/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:48:1: module "Qt.labs.settings" is not installed

QtWebEngine: component error: file:///snap/icloud-for-linux/166/usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:47:1: module "Qt.labs.folderlistmodel" is not installed
```

This is not urgent, as I can move the files through other means. Thanks!

**Comment by MarcusTomlinson** [comment]
Hi @LevBernstein, thanks for the report. This is now fixed in version 0.9 of the snap.
