### ISSUE TITLE
Sent emails don't close or indicate that they have sent

### ISSUE THREAD

**Issue by LevBernstein** [cross-platform/icloud-for-linux#27]
Hello,
This isn't a new issue for me and is very minor, but still worth mentioning. Running ParrotOS 4.10, KDE Plasma 5. Whenever I press the send button on an email I have written, the wheel next to the attach button will spin for a second and then freeze. When it has frozen, that means the email has sent, I have found. Despite having sent, the window containing this new message I have composed does not close; it freezes, and all buttons on it stop responding. I can still close the window, though. Despite freezing like this, the message still sends normally.

Thank you for resolving the other issue I raised; I appreciate it.

**Comment by MarcusTomlinson** [comment]
Hi @LevBernstein, thanks for the report. This is now fixed in version 0.10 of the snap :)

**Comment by LevBernstein** [comment]
Thanks!
