### ISSUE TITLE
Scaling still not working

### ISSUE THREAD

**Issue by loeffel-io** [cross-platform/icloud-for-linux#28]
Thanks for this beautiful app, but please just fix the scaling - way to small for uhd

**Comment by MarcusTomlinson** [comment]
Hi @loeffel-io could you please try launching from the terminal like so:

QT_AUTO_SCREEN_SCALE_FACTOR=1 icloud-for-linux.notes

and let me know if that fixes things?

**Comment by MarcusTomlinson** [comment]
Hmm, ok just tried this, doesn't work.

In the meantime, while I try to find a better solution for this, you could run the apps like this:

`QT_SCALE_FACTOR=x icloud-for-linux.notes`

Where `x` is the scale factor of your display. E.g. scale factor 2 = 200% scaling

**Comment by MarcusTomlinson** [comment]
This is now fixed in version 0.11.
