### ISSUE TITLE
Not using OS pointer

### ISSUE THREAD

**Issue by llano-dan** [cross-platform/icloud-for-linux#30]
Minor annoyance, but I'm in Ubuntu 20.04. The pointer cursor (hand) is different from that of the OS.

I've seen this in different snaps.
![IMG_0163](https://user-images.githubusercontent.com/41120327/103139592-22797000-46de-11eb-9035-6012b0be36a5.JPEG)

**Comment by azuredusk10** [comment]
I'd also like to add to this. My cursor is half the size in the iCloud apps compared to across the rest of my system:
![image](https://user-images.githubusercontent.com/18142893/142761891-e3eff6ba-cd46-43a1-bffa-3d5e1557f309.png)

**Comment by MarcusTomlinson** [comment]
Could you try v0.12 - Run `snap refresh icloud-for-linux`.

**Comment by azuredusk10** [comment]
This seems to have solved the problem - thank you!
