### ISSUE TITLE
Crash on Debian

### ISSUE THREAD

**Issue by JMR62** [cross-platform/icloud-for-linux#34]
I have get a crash on Debian when running _snap run icloud-for-linux.drive_ ( same happens with notes...)
a new window is opening then the complete system is freezing (I can open a new terminal and restart)
Before the crash these line appears in the command window:
**Messages in user log**
... Jan 19 18:31:48 kibox icloud-for-linux_drive.desktop[8704]: WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Jan 19 18:31:49 kibox icloud-for-linux_drive.desktop[8704]: Qt: Session management error: None of the authentication protocols specified are supported
Jan 19 18:31:51 kibox icloud-for-linux_drive.desktop[8704]: Sandboxing disabled by user....

**If of any use Messages in syslog when it crash (not the same trial but same messages)**
Jan 19 17:35:18 kibox kernel: [  487.281943] kauditd_printk_skb: 20 callbacks suppressed
Jan 19 17:35:18 kibox kernel: [  487.281944] audit: type=1400 audit(1611074118.409:69): apparmor="DENIED" operation="capable" profile="/snap/core/10583/usr/lib/snapd>
Jan 19 17:35:21 kibox kernel: [  490.039130] audit: type=1326 audit(1611074121.165:70): auid=1000 uid=1000 gid=1000 ses=8 subj==snap.icloud-for-linux.drive (enforce)>
Jan 19 17:35:21 kibox kernel: [  490.039142] audit: type=1326 audit(1611074121.165:71): auid=1000 uid=1000 gid=1000 ses=8 subj==snap.icloud-for-linux.drive (enforce)>
Jan 19 17:35:21 kibox kernel: [  490.039161] audit: type=1326 audit(1611074121.165:72): auid=1000 uid=1000 gid=1000 ses=8 subj==snap.icloud-for-linux.drive (enforce)>
Jan 19 17:35:21 kibox kernel: [  490.039206] audit: type=1326 audit(1611074121.165:73): auid=1000 uid=1000 gid=1000 ses=8 subj==snap.icloud-for-linux.drive (enforce)>
Jan 19 17:35:29 kibox kernel: [  497.974949] i915 0000:00:02.0: [drm] GPU HANG: ecode 7:1:8edcfc79, in icloud-for-linu [41879]
Jan 19 17:35:29 kibox kernel: [  497.974954] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Jan 19 17:35:29 kibox kernel: [  497.974956] Please file a _new_ bug report at https://gitlab.freedesktop.org/drm/intel/issues/new.
Jan 19 17:35:29 kibox kernel: [  497.974958] Please see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
Jan 19 17:35:29 kibox kernel: [  497.974959] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
Jan 19 17:35:29 kibox kernel: [  497.974961] The GPU crash dump is required to analyze GPU hangs, so please always attach it.
Jan 19 17:35:29 kibox kernel: [  497.974963] GPU crash dump saved to /sys/class/drm/card0/error
Jan 19 17:35:29 kibox kernel: [  497.975063] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
Jan 19 17:35:29 kibox kernel: [  498.076311] i915 0000:00:02.0: [drm] icloud-for-linu[41879] context reset due to GPU hang

Thanks for any help.

**Comment by MarcusTomlinson** [comment]
Looks like you're facing this: https://bugs.mageia.org/show_bug.cgi?id=27159

If you google "GPU HANG: ecode 7:1:8edcfc79" you'll see a bunch of related reports. Essentially sounds like you need a kernel update.

**Comment by JMR62** [comment]
Thanks.
You are right some last Debian update did a mess it seems... 
sorry to incriminate to fast icloud for linux

**Comment by MarcusTomlinson** [comment]
No problem. Let me know if you find a solution!
