### ISSUE TITLE
product installs but will not start

### ISSUE THREAD

**Issue by MikeVaccaro** [cross-platform/icloud-for-linux#35]
from the Gui when I start any of the Icloud modules, nothing happens.
from the command line, I do snap list and it shows up
I try snap run icloud-for-linux and it says
error: cannot find app "icloud-for-linux" in "icloud-for-linux"

please advise!

**Comment by MarcusTomlinson** [comment]
Hi @MikeVaccaro, the snap is made up of a number of applications (mail, contacts, calendar, etc.). In order to run one of them you’ll need to execute icloud-for-linux.<app> (E.g. icloud-for-linux.mail)

typing “ icloud-for-linux.” then pressing tab will display your options.

**Comment by kcossabo** [comment]
thank you. for the new / novice this might be put on the intro page or readme. I was about to give up.
