### ISSUE TITLE
(Feature Request) Icloud on Flatpak

### ISSUE THREAD

**Issue by dtantono** [cross-platform/icloud-for-linux#37]
Hi
Is this possible for this app available on flatpak as well?

**Comment by MarcusTomlinson** [comment]
I don’t have any plans to do this but I’m happy to accept a PR for this.

**Comment by dtantono** [comment]
I see, it is completed. where is the URL?

**Comment by MarcusTomlinson** [comment]
> I see, it is completed. where is the URL?

Closed by mistake.

**Comment by alexpetrean80** [comment]
updates on this?

**Comment by MarcusTomlinson** [comment]
My intention for this project is for it to be a snap only. My suggestion, for anyone wanting to re-purpose this for other package managers, is to fork.
