### ISSUE TITLE
Doesn't seem to run through VNC/xfce4. Is there a command line mode?

### ISSUE THREAD

**Issue by r-a-i** [cross-platform/icloud-for-linux#39]
Thank you so much for developing this great utility. It will be amazing to have this functionality!

I installed via sudo snap install icloud-for-linux.
When I log into my Ubuntu 18.x via VNC with xfce4 desktop I can see all the iCloud apps in the Applications/Other menu. 
However, when I click on any of the iCloud apps, nothing happens. 

Is there any log in or configuration step that I should perform. The readme.md is beautiful but doesn't say much. 

Is there a way to run it from the command line? My specific needs are to do a batch download of photos. I could do a full cloudDrive batch download too.

**Comment by MarcusTomlinson** [comment]
Hi @r-a-i, so this app is really just an embedded browser pointing at https://www.icloud.com/.

For your one-shot purpose, I’d just recommend navigating there in your browser.

If you’d like to pursue the app route further, you can open the terminal, run:

`icloud-for-linux.drive`

and share the output here.

**Comment by r-a-i** [comment]
Thanks Marcus. For the time being, I found a workaround by rsyncing from my Mac to Linux. It's clumsy but works for now. I'll keep an eye on this project as it matures.
