### ISSUE TITLE
can’t upload file from drive, says it’s a folder

### ISSUE THREAD

**Issue by PaulLerner** [cross-platform/icloud-for-linux#40]
Hi, it’s pretty much all in the title: when I try to upload a file (only tried PDF) from drive there’s an error saying something like ‘cannot upload folder, only files are supported’ (even though it’s a file obviously)
Everything works fine from https://www.icloud.com/ (unlike my previous issue ;) )

# Specs
```
Ubuntu 20.04.2 LTS
64 bits
```
Not sure where to find `icloud-for-linux.drive` version

**Comment by MarcusTomlinson** [comment]
Could you try v0.12 - Run `snap refresh icloud-for-linux`.
