### ISSUE TITLE
tiny mouse on 4k screen

### ISSUE THREAD

**Issue by tosziro** [cross-platform/icloud-for-linux#43]
![Zrzut ekranu z 2021-06-23 20-50-20](https://user-images.githubusercontent.com/41963712/123152229-a9788c80-d464-11eb-896a-c409f80fa8c4.png)

Mouse cursor is very small on 4k screen. Could you please fix this?
X11 Ubuntu 21.04

Its exacly like this: https://forum.snapcraft.io/t/very-ugly-cursor-for-spotify-and-kde-snaps/17118/3

> snap connections icloud-for-linux
Interface               Plug                                     Slot                     Notes
browser-support         icloud-for-linux:browser-support         :browser-support         -
desktop                 icloud-for-linux:desktop                 :desktop                 -
desktop-legacy          icloud-for-linux:desktop-legacy          :desktop-legacy          -
home                    icloud-for-linux:home                    :home                    -
network                 icloud-for-linux:network                 :network                 -
opengl                  icloud-for-linux:opengl                  :opengl                  -
screen-inhibit-control  icloud-for-linux:screen-inhibit-control  :screen-inhibit-control  -
x11                     icloud-for-linux:x11                     :x11   

icloud-for-linux is is not connected to gtk-common-themes

**Comment by logicito** [comment]
I have a 1920 x 1200 screen, and have the same issue, super small mouse cursor, please fix it, your app is great!! Thank you

**Comment by MarcusTomlinson** [comment]
This should be fixed in v0.12 now. Please run `snap refresh icloud-for-linux`.
