### ISSUE TITLE
can't see files from mounted partition

### ISSUE THREAD

**Issue by fixxs75** [cross-platform/icloud-for-linux#45]
In mail, I can't see my files from a mounted partition on home/Datos.

**Comment by cuvy** [comment]
It looks to me like this might just be a container that presents a web view. If you log into icloud from a browser, the interface looks exactly the same. I'd say the icloud content is never available or accessible via any sort of filesystem (which is a shame, but i'd say it would probably be very difficult to reverse the protocols to allow this)

**Comment by devzer01** [comment]
yeah what a waste of time???
