### ISSUE TITLE
Can we have some documentation, please?

### ISSUE THREAD

**Issue by MHohenberg** [cross-platform/icloud-for-linux#46]
Can we have some information about what this actually does? I was looking for a sync functionality similar to owncloud/dropbox/mega ... but that is not what this program seems to do? Or maybe there is a hidden switch that I have not found yet?

Some basic documentation, e.g. in the README.md, would allow people to gauge usefulness against their use-case and is a pretty standard thing to do.

**Comment by scribbles** [comment]
This snap simply opens a Qt window and goes to the iCloud URL for each app. It's exactly what is available to you via a web browser.
