### ISSUE TITLE
Can't run on Debian 11

### ISSUE THREAD

**Issue by bepstein111** [cross-platform/icloud-for-linux#47]
Brand new Debian 11 install, I installed apple-music-for-linux and got that to work fine, but icloud-for-linux (installed with and without --devmode as suggested by #6) is giving me the following error upon running `/snap/bin/icloud-for-linux.drive &`:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
QGLXContext: Failed to create dummy context
Sandboxing disabled by user.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 

[2]  + 23634 abort      /snap/bin/icloud-for-linux.drive
[23784:23784:0100/000000.258216:ERROR:zygote_linux.cc(621)] Zygote could not fork: process_type renderer numfds 3 child_pid -1
[23784:23784:0100/000000.258259:ERROR:zygote_linux.cc(653)] write: Broken pipe (32)

```

Just unsure how to proceed from here. Any help is appreciated. Thanks!
-bepstein111

PS. this doesn't seem related to #34 or #36 to me, but I could be wrong, sorry if that's the case!  It does seem similar to #22, but I'm running debian, not ubuntu (although ubuntu IS debian-based...), but I'd rather find the issue than reinstall for the second time in a week.

**Comment by MarcusTomlinson** [comment]
Could you try v0.12 - Run `snap refresh icloud-for-linux`.
