### ISSUE TITLE
Does not load on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by simpson-sean** [cross-platform/icloud-for-linux#49]
SYSTEM DETAILS

Operating System: openSUSE Tumbleweed 20220214
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.8-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i7-11370H @ 3.30GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics

ISSUE
Installs from SNAPCRAFT just fine, at least no errors reported.  Apps will launch, seem to try to load, and just don't.

**Comment by MarcusTomlinson** [comment]
Could you try re-installing like this:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

If this still doesn't work, try `snap install icloud-for-linux --devmode` in place of the third step above.

If this does not work, please run `icloud-for-linux.notes` from the terminal and share the output here.

Thanks.
