### ISSUE TITLE
Segfault starting any of the apps (Arch)

### ISSUE THREAD

**Issue by hilpara** [cross-platform/icloud-for-linux#5]
When ever I try to launch any of the icloud apps, I will get a  segmentation fault:

`[  209.006715] audit: type=1326 audit(1578734809.591:77): auid=1000 uid=1000 gid=985 ses=2 pid=2111 comm="qmlscene" exe="/snap/icloud-for-linux/59/usr/lib/qt5/bin/qmlscene" sig=0 arch=c000003e syscall=272 compat=0 ip=0x7f3636e31839 code=0x50000
[  209.120094] audit: type=1701 audit(1578734809.704:78): auid=1000 uid=1000 gid=985 ses=2 pid=2111 comm="qmlscene" exe="/snap/icloud-for-linux/59/usr/lib/qt5/bin/qmlscene" sig=6 res=1
[  209.127526] audit: type=1130 audit(1578734809.714:79): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-2112-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  209.819975] qmlscene[1930]: segfault at 0 ip 00007f3631283a11 sp 00007fff0173ea20 error 4 in libQt5XcbQpa.so.5.9.5[7f36311e3000+fe000]
[  209.819983] Code: e8 d4 2c f9 ff 48 85 db 75 e7 4c 89 ea 4c 89 f6 31 ff e8 f2 2d f9 ff 4c 89 ef 49 89 c7 e8 d7 20 f9 ff 4c 89 f7 e8 9f f0 f8 ff <41> 8b 07 85 c0 7e 21 45 31 e4 31 db 0f 1f 00 49 8b 47 08 83 c3 01
[  209.820039] audit: type=1701 audit(1578734810.404:80): auid=1000 uid=1000 gid=985 ses=2 pid=1930 comm="qmlscene" exe="/snap/icloud-for-linux/59/usr/lib/qt5/bin/qmlscene" sig=11 res=1
[  209.827923] audit: type=1130 audit(1578734810.414:81): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3-2134-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  210.062686] audit: type=1131 audit(1578734810.648:82): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@2-2112-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  210.481931] audit: type=1131 audit(1578734811.068:83): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@3-2134-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
`
I'm using Arch and as a desktop XFCE (4.14).

**Comment by hilpara** [comment]
If it helps, here is the stack trace:
`systemd-coredump[6421]: Process 6272 (qmlscene) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 6272:
                                                  #0  0x00007f97a97f2a11 n/a (libQt5XcbQpa.so.5 + 0xa0a11)
                                                  #1  0x00007f97b06bcb21 n/a (libQt5Gui.so.5 + 0x1d4b21)
                                                  #2  0x00007f97b06bf99d n/a (libQt5Gui.so.5 + 0x1d799d)
                                                  #3  0x00007f97b06bfa2a n/a (libQt5Gui.so.5 + 0x1d7a2a)
                                                  #4  0x00007f97b069697d _ZNK5QFont13defaultFamilyEv (libQt5Gui.so.5 + 0x1ae97d)
                                                  #5  0x00007f9766255e84 _ZN15QtWebEngineCore17WebEngineSettings12initDefaultsEb (libQt5WebEngineCore.so.5 + 0x728e84)
                                                  #6  0x00007f9772fa7fbc n/a (libQt5WebEngine.so.5 + 0x28fbc)
                                                  #7  0x00007f9772fa93cd _ZN22QQuickWebEngineProfile14defaultProfileEv (libQt5WebEngine.so.5 + 0x2a3cd)
                                                  #8  0x00007f9772fb0dba _ZN26QQuickWebEngineViewPrivateC1Ev (libQt5WebEngine.so.5 + 0x31dba)
                                                  #9  0x00007f9772fb1c9b _ZN19QQuickWebEngineViewC2EP10QQuickItem (libQt5WebEngine.so.5 + 0x32c9b)
                                                  #10 0x00007f97731e927b n/a (libqtwebengineplugin.so + 0x427b)
                                                  #11 0x00007f97b16fd962 _ZNK8QQmlType6createEPP7QObjectPPvm (libQt5Qml.so.5 + 0x265962)
                                                  #12 0x00007f97b176e146 _ZN17QQmlObjectCreator14createInstanceEiP7QObjectb (libQt5Qml.so.5 + 0x2d6146)
                                                  #13 0x00007f97b17703da _ZN17QQmlObjectCreator18setPropertyBindingEPK16QQmlPropertyDataPKN3QV412CompiledData7BindingE (libQt5Qml.so.5 + 0x2d83da)
                                                  #14 0x00007f97b1770e11 _ZN17QQmlObjectCreator13setupBindingsEb (libQt5Qml.so.5 + 0x2d8e11)
                                                  #15 0x00007f97b176dba6 _ZN17QQmlObjectCreator16populateInstanceEiP7QObjectS1_PK16QQmlPropertyData (libQt5Qml.so.5 + 0x2d5ba6)
                                                  #16 0x00007f97b176e97c _ZN17QQmlObjectCreator14createInstanceEiP7QObjectb (libQt5Qml.so.5 + 0x2d697c)
                                                  #17 0x00007f97b1771c6c _ZN17QQmlObjectCreator6createEiP7QObjectP26QQmlInstantiationInterrupt (libQt5Qml.so.5 + 0x2d9c6c)
                                                  #18 0x00007f97b16e8408 _ZN20QQmlComponentPrivate11beginCreateEP15QQmlContextData (libQt5Qml.so.5 + 0x250408)
                                                  #19 0x00007f97b16e674f _ZN13QQmlComponent6createEP11QQmlContext (libQt5Qml.so.5 + 0x24e74f)
                                                  #20 0x0000555e5f8a7c5a n/a (qmlscene + 0x5c5a)
                                                  #21 0x00007f97af2a6b97 n/a (/lib/x86_64-linux-gnu/libc-2.27.so + 0x21b97)
`

**Comment by MarcusTomlinson** [comment]
Could you try re-installing like this:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

If this still doesn't work, try `snap install icloud-for-linux --devmode` in place of the third step above.
