### ISSUE TITLE
Upload files JSON-RPC error

### ISSUE THREAD

**Issue by pondakun** [cross-platform/icloud-for-linux#50]
I try to upload some document's and he upload 2 of them and ask me to .zip when i try to multi files (all pdf)
in terminal the error i get is:
 js: A JSON-RPC registration was not found for method `MeCardServiceToChildProtocol-didFetchMeCard`.

**Comment by MarcusTomlinson** [comment]
Could you try v0.12 - Run `snap refresh icloud-for-linux`.
