### ISSUE TITLE
Packaging as a deb file

### ISSUE THREAD

**Issue by dtantono** [cross-platform/icloud-for-linux#51]
Hi
Is there any possibility for deb file for this app?

**Comment by MarcusTomlinson** [comment]
I don’t have any plans to do this myself but happy to review a PR.

**Comment by Free-Radical** [comment]
I'll second that; anything other than a Snap would be fantastic.
PS whats a "PR"?

**Comment by poldy79** [comment]
PR == Pull Request (on github)

**Comment by dtantono** [comment]
I see, it is completed. where is the URL?

**Comment by MarcusTomlinson** [comment]
> I see, it is completed. where is the URL?

Closed by mistake.

**Comment by MarcusTomlinson** [comment]
My intention for this project is for it to be a snap only. My suggestion, for anyone wanting to re-purpose this for other package managers, is to fork.
