### ISSUE TITLE
All iCloud features quit working on Ubuntu

### ISSUE THREAD

**Issue by Halonk** [cross-platform/icloud-for-linux#54]
Well....
This took off a bit for a newbie like me, create an account on GitHub and all, just to report an error. OK, but that is what I wanted to tell. Ubuntu 20.04. Downloaded iCloud from snap and had to log in on a few of them and they all worked fine. Now, nothing, dark window, "this seems to take a long time" "wait" or "force quit" where the last is the only solution. I have not written a code longer than "sudo apt get install... and then something" in all my life so here you have a hopeless case in that departement but maybe....?

**Comment by MarcusTomlinson** [comment]
Could you try re-installing like this:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```
