### ISSUE TITLE
Can't login with Chinese icloud account

### ISSUE THREAD

**Issue by ShoiLyaung** [cross-platform/icloud-for-linux#56]
When I log in with my account,it mentioned me with:
> This Apple ID can’t sign in to iCloud.com.
To sign in with this Apple ID, go to iCloud.com.cn."

But the link below can only be opened in a browser. So I'm stuck in the login page.
I considered if it is possible to provide a way to log in by `iCloud.com.cn` instead of  `iCloud.com`

**Comment by FengZeHe** [comment]
> 
I also met this problem. Have you solved it?

**Comment by ShoiLyaung** [comment]
No, still waiting for reply.

**Comment by MarcusTomlinson** [comment]
Selecting a manual TLD is now possible via `~/snap/icloud-for-linux/common/tld` in version 0.13+ of the snap.

For example:

```
mkdir -p ~/snap/icloud-for-linux/common
echo ".com.cn" > ~/snap/icloud-for-linux/common/tld
```
