### ISSUE TITLE
Question about recent commit

### ISSUE THREAD

**Issue by abraithwaite** [cross-platform/icloud-for-linux#57]
I'm looking for OSS to access icloud when I stumbled upon this repo.

I happened to notice that in the last commit, the ability to replace the icloud TLD with one controlled by a file in the snap configuration directory.

I presume this is intended to aid development, but it looks concerning from a privacy point-of-view, considering the program could easily replace that file at runtime or perhaps even at install time.

Can you share what the intentions are for this commit?

https://github.com/cross-platform/icloud-for-linux/commit/949b3d75ba270b24ad3ec362c20b3028245630e1

**Comment by MarcusTomlinson** [comment]
Hey, thanks for this. This was added recently to resolve: https://github.com/cross-platform/icloud-for-linux/issues/56.
