### ISSUE TITLE
Should you ignore dump directory via .gitignore?

### ISSUE THREAD

**Issue by jzombie** [cross-platform/icloud-for-linux#58]
Hello, I was just passing through and noticed the dump directory in the git repo and think it should be ignored.

https://github.com/cross-platform/icloud-for-linux/tree/master/dump/config/icloud-for-linux/Local%20Storage/leveldb

**Comment by MarcusTomlinson** [comment]
Hey, thanks for the report! It does look odd indeed, but it was added intentionally :)

https://github.com/cross-platform/icloud-for-linux/commit/f503812675bdb1c75a3bbba702f387588409ac46
