### ISSUE TITLE
Mount iCloud drive to filesystem

### ISSUE THREAD

**Issue by felkru** [cross-platform/icloud-for-linux#59]
I would love the App to automatically add a iCloud directory somewhere in your filesystem, so that you can access iCloud Drive more easily.

**Comment by staringatphones** [comment]
To be clear, there is no "functional connection to iCloud" in this project. This application is just an Electron app, which means it's just a Chromium browser pointed to iCloud.com. You can log into iCloud in any browser and obtain the same functionality.

**Comment by agail** [comment]
I came here as well thinking it would actually mount the icloud drive, this is only a QT wrapper for the web interface, nothing more.

**Comment by 2gn** [comment]
> I came here as well thinking it would actually mount the icloud drive, this is only a QT wrapper for the web interface, nothing more.

It's not QT but Electron

**Comment by moritz-t-w** [comment]
I've looked around and this is all I could find:
https://github.com/mandarons/icloud-drive-docker

**Comment by MarcusTomlinson** [comment]
This won't be a feature supported in this web app
