### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by jakubkameleon** [cross-platform/icloud-for-linux#6]
Hi could I ask for help? I have Installed with snap, on my Debian 10. 
![icloud](https://user-images.githubusercontent.com/33316966/75113449-5adb9800-564e-11ea-934f-069d1a0e3c72.png)
How to use this, afetr clik nothing happen. In htop it show just for a moment and disapear.
![proces](https://user-images.githubusercontent.com/33316966/75113503-c160b600-564e-11ea-9e0f-510c047eb784.png)

**Comment by MarcusTomlinson** [comment]
Try clearing the cache like so: `rm -rf ~/snap/icloud-for-linux/`, then relaunching the snap.

**Comment by jakubkameleon** [comment]
I celaned cache and try launch iclud Drive, this process apear only for a while :(
![Screenshot from 2020-02-23 17-57-44](https://user-images.githubusercontent.com/33316966/75116228-5cb15580-5666-11ea-8917-8e821dba5117.png)

**Comment by MarcusTomlinson** [comment]
Could you please run drive from the terminal like this: `snap run icloud-for-linux.drive` and paste the output here.

**Comment by jakubkameleon** [comment]
Yes, ofcourse:

`pretender@ThinkPad:~$ snap run icloud-for-linux.drive
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Qt: Session management error: None of the authentication protocols specified are supported
"/home/pretender/iclouddrive" does not exist.
"/home/pretender/iCloud Drive" does not exist.
[14215:14288:0223/180424.068923:ERROR:address_tracker_linux.cc(153)] Could not create NETLINK socket: Operation not permitted
[14215:14297:0223/180424.073716:FATAL:udev_linux.cc(20)] Check failed: monitor_. 
#0 0x7fb48ab97aee <unknown>
#1 0x7fb48abaa0e2 <unknown>
#2 0x7fb48a3ce5d8 <unknown>
#3 0x7fb48b5ba772 <unknown>
#4 0x7fb48ac0ea83 <unknown>
#5 0x7fb48abb2a00 <unknown>
#6 0x7fb48abb4058 <unknown>
#7 0x7fb48abb43eb <unknown>
#8 0x7fb48abb5aa2 <unknown>
#9 0x7fb48abb1da8 <unknown>
#10 0x7fb48abce77b <unknown>
#11 0x7fb48a46c978 <unknown>
#12 0x7fb48a46cf2b <unknown>
#13 0x7fb48abe6588 <unknown>
#14 0x7fb48abe25eb <unknown>
#15 0x7fb4b13cb6db start_thread
#16 0x7fb4b1a9088f clone
`
I miss something ?

**Comment by MarcusTomlinson** [comment]
Hmm, try a re-install:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

If this still doesn't work, try `snap install icloud-for-linux --devmode` in place of the third step above.

**Comment by jakubkameleon** [comment]
Now it works :) thanks a lot!!!
**snap install icloud-for-linux --devmode**
Installation devmode, this app work correct. Great! I tried other similar app it also works, but after quit the process was still running. In this case process end after quit app.
