### ISSUE TITLE
Failed to load gtk module on startup

### ISSUE THREAD

**Issue by opentrail** [cross-platform/icloud-for-linux#62]
On start up I receive these messages:
➜  ~ icloud-for-linux.drive
Gtk-Message: 09:58:06.703: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 09:58:06.704: Failed to load module "colorreload-gtk-module"
[8686:0406/095813.067798:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

**Comment by MarcusTomlinson** [comment]
Please try the latest snap version, a fair bit has been fixed.
