### ISSUE TITLE
files within icloud drive don't open when double clicked

### ISSUE THREAD

**Issue by sepoff72** [cross-platform/icloud-for-linux#64]
i noticed that i can view all my files in icloud drive which is great!  For pdf documents i can see the thumbnail of the document which is great.  But when i double click the pdf in your app, it appears to open, but there is nothing there.
![Screenshot from 2023-04-23 13-19-45](https://user-images.githubusercontent.com/131610763/233854725-1fceef76-ec8f-4749-8a6f-844ea58b0c33.png)

Whereas when I do this on my iphone the pdf opens right up. 

Thank You!!!!

**Comment by MarcusTomlinson** [comment]
Please try the latest snap version, a fair bit has been fixed.
