### ISSUE TITLE
iCloud Drive Not Downloading

### ISSUE THREAD

**Issue by ashbytaylors** [cross-platform/icloud-for-linux#67]
Hi,

I see this has been an issue previously but I'm also experiencing it in v0.13 of icloud-for-linux.

I can see the following error message in DMESG whenever I click on a file to download. All else appears to be fine. I'm running on the latest version of Armbian on a Rock 4c+.

`[44212.647312] audit: type=1400 audit(1690572461.567:183): apparmor="DENIED" operation="open" profile="snap.icloud-for-linux.drive" name="/run/mount/utab" pid=5995 comm="icloud-for-linu" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

Hope you can help,
Thanks

**Comment by ashbytaylors** [comment]
Hi,

I've been investigating this further and if I run icloud-for-linux.drive from a command line I see the following error message appear when I request a download:

"Gtk-WARNING **: 18:13:21.022: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files"

I'm going to try and reinstall using --devmode to see if that makes any difference.

**Comment by ashbytaylors** [comment]
Hey - I think I've found the issue. Looks like it doesn't work with LXDE. Tried with OpenBox and Gnome, works fine! 

There is no xdg-desktop-portal-xxxx for LXDE

**Comment by CmdrChaos** [comment]
I am also experiencing the same issue trying to download a file.  Error meg:

(icloud-for-linux:7304): Gtk-WARNING **: 18:08:08.815: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

System Info:
Linux pluralZalpha 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Debian GNU/Linux 11 (bullseye)
GNOME Version: 3.38.5

**Comment by MarcusTomlinson** [comment]
Please try the latest snap version, a fair bit has been fixed.
