### ISSUE TITLE
snapd installation ok - snap does not work

### ISSUE THREAD

**Issue by wgp-git** [cross-platform/icloud-for-linux#68]
Trying to install icloud-for-linux on MX Linux 23 Libretto

- Installing snapd worked
- Executing `snap help` worked
- Executing `snap list` results in error message: error: cannot list snaps: cannot communicate with server: Get "http://localhost/v2/snaps": dial unix /run/snapd.socket: connect: no such file or directory

What do I wrong?

**Comment by MarcusTomlinson** [comment]
Please try the latest snap version, a fair bit has been fixed.
