### ISSUE TITLE
Is it possible to sync the files in the icloud drive to a local folder? say ~/icloud_drive

### ISSUE THREAD

**Issue by sam02151015** [cross-platform/icloud-for-linux#7]
I am very interested in getting a dropbox alternative on linux using icloud. Is it possible to sync the files in the icloud drive to a local folder? say ~/icloud_drive

**Comment by MarcusTomlinson** [comment]
While theoretically it could be possible to implement such a feature from the ground up, it is too far out of scope for this project unfortunately.

**Comment by tagMacher** [comment]
This app seems pointless in that the functionality provided already is available through any browser on Linux. Sync / access from Linux as a mounted storage would be the only reason to use it, IMO, but the developer has marked it "wontfix".
