### ISSUE TITLE
Firefox bookmarks

### ISSUE THREAD

**Issue by schlagmichdoch** [cross-platform/icloud-for-linux#70]
I'm looking for a possibility to sync Firefox bookmarks with iOS Safari bookmarks.

On Windows, the iCloud application is able to sync Firefox bookmarks to iCloud. [1] As iOS Safari saves its bookmarks to iCloud this results in Firefox bookmarks and Safari bookmarks being in sync.

Do you think it is possible to integrate this functionality into this app?
Is this application talking itself to the iCloud API or is this rather containerized view of the apps on icloud.com? 

[1]
<img src="https://cdn.mos.cms.futurecdn.net/r7t6qKM8pprzNBH5Wgjcvg-1920-80.jpg.webp" width="400px"/>

**Comment by MarcusTomlinson** [comment]
The Windows app is an official Apple product, this is not, it's simply a webview pointing to iCloud.com. Thus, this won't be a feature supported in this app unfortunately, sorry about that.
