### ISSUE TITLE
Can not login to icloud.com.cn

### ISSUE THREAD

**Issue by FLAYhhh** [cross-platform/icloud-for-linux#71]

**Comment by xiaod-dev** [comment]
yeah. I found the same issue. Apple has An Independent service URL for Chinese Customers.https://www.icloud.com.cn/
![image](https://github.com/cross-platform/icloud-for-linux/assets/21277644/28a3e640-e57d-4312-8f0f-526e42ea3ada)
@FLAYhhh  Could you help provide a Service URL configuration feature?

**Comment by MarcusTomlinson** [comment]
Selecting a manual TLD is now possible again via `~/snap/icloud-for-linux/common/tld` in version 0.21+ of the snap.

For example:

```
mkdir -p ~/snap/icloud-for-linux/common
echo ".com.cn" > ~/snap/icloud-for-linux/common/tld
```
