### ISSUE TITLE
Is there any way to increase text size/zoom in?

### ISSUE THREAD

**Issue by hujberhunor** [cross-platform/icloud-for-linux#72]

**Comment by MarcusTomlinson** [comment]
Does Ctrl + not work?

**Comment by hujberhunor** [comment]
No. 
But as it seems crtl + is not working in Caprine (electron based). So i think i have some problem with electron.

**Comment by MarcusTomlinson** [comment]
This won't be a feature supported by this web app, sorry. But do try the latest snap, scaling may be better now.
