### ISSUE TITLE
icloud-for-linux cannot access Apple

### ISSUE THREAD

**Issue by pcoreyster** [cross-platform/icloud-for-linux#73]
Starting Wednesday, June 6, 2024, the following image (graphic) was experience as the app was starting up
![image](https://github.com/cross-platform/icloud-for-linux/assets/27238072/4cc8ccdf-8a8b-4f24-a181-b05b23bc9444)

I am using POP!_OS 22.04 with Firefox installed via flatpak.    This configuration has been working for about two years, but recently (for the last 2 days) all the snap apps (shipped via snapd) launch without any web page.

I can access the site directly via icloud.com using the same system/browser/operating system.

**Comment by hotdogthemovie** [comment]
I have a fresh install of Ubuntu 24.04.  Installed iCloud app from the App Center, and all the various apps display the above error as well.

**Comment by iop90cwl** [comment]
Dang. The day after I install Arch and start getting comfy this stops working. That sucks

**Comment by juergenbader-hh** [comment]
Same problem on elementaryOS - same picture. I would like to avoid using other browsers instead of icloud-for-linux

**Comment by lfhoward** [comment]
Same exact problem using the Brave browser.

**Comment by WiteWulf** [comment]
Getting the same problem. Was on ubuntu 22, so upgrade to 24.04. Still getting the problem.

App Centre reports version 0.13 installed, which is interesting as that's no listed on this repo.

**Comment by davidil28** [comment]
Same issue on Ubuntu 22.04 Jammy Jellyfish (x86-64)

**Comment by mikebharris** [comment]
Same on Ubuntu 22.04.4 LTS.  Worked initially a few weeks back, now doesn't.  I have various browsers installed, but it's erroring whichever I make default.  I have Firefox 127.0 (64-bit), Chrome 125.0.6422.141, Edge 125.0.2535.92.

**Comment by abulygin** [comment]
I started having the same problems a few days ago. I was moved to web UI as a temporary solution. It would be great if this is fixed. I like the iCloud app on Ubuntu.

**Comment by MarcusTomlinson** [comment]
Hey guys, I'll have a look at this over the weekend.

**Comment by pcoreyster** [comment]
Marcus, thank you.   I have introduced many of my friends/peers to this snap app as these individual switch from macOS to Ubuntu/Pop!_OS.

**Comment by MarcusTomlinson** [comment]
Fixed in 0.14

**Comment by adelaydeelsevier** [comment]
> Fixed in 0.14

Thanks @MarcusTomlinson - interested in what caused the issue, if you've the time to explain.  Otherwise, thanks for fixing it so quickly. :)

**Comment by MarcusTomlinson** [comment]
> > Fixed in 0.14
> 
> Thanks @MarcusTomlinson - interested in what caused the issue, if you've the time to explain. Otherwise, thanks for fixing it so quickly. :)

It appears Apple have decided to get smart about browser detection - beyond just reading the User Agent. Electron is clearly not a browser they want to support.

The fix was to move to a C++ app and use a system native webview instead. On the up side, it'll definitely be more efficient this way, on the down side, it'll likely have a bunch of new issues of its own.

**Comment by jptraverso26** [comment]
I'm running 0.19 and still suffering from this problem.

**Comment by MarcusTomlinson** [comment]
> I'm running 0.19 and still suffering from this problem.

Could you try re-installing like this:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

**Comment by jptraverso26** [comment]
I followed your instructions and get the same result

**Comment by MarcusTomlinson** [comment]
> I followed your instructions and get the same result

Can't say what's wrong there but please try 0.20, see if it resolves for you.

**Comment by Kymer0615** [comment]
For anyone who has this issue, `icloud-for-linux.reminders --no-sandbox` in the terminal does the trick for me :)

**Comment by juergenbader-hh** [comment]
Hi,

thanks for the instruction. It solved the problem.

Now everything runs perfect again.

Thanks again

Juergen


Am Fri, 21 Jun 2024 08:42:25 -0700, Marcus Tomlinson ***@***.***> schrieb:
 
 


I'm running 0.19 and still suffering from this problem.


Could you try re-installing like this:

snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux

**Comment by pcoreyster** [comment]
Thank for all the work Marcus.
