### ISSUE TITLE
Doesn't work reports not compatible

### ISSUE THREAD

**Issue by chest069** [cross-platform/icloud-for-linux#74]
I was excited for this but when I try to run it I get browser not compatible, Is there a way to fix this so when clicking on an icon it knows I am using a compatible browser?

Thanks for making this.

**Comment by souremperor** [comment]
@chest069 everyone is having that issue right now.

https://github.com/cross-platform/icloud-for-linux/issues/73

**Comment by MarcusTomlinson** [comment]
Fixed in 0.14
