### ISSUE TITLE
iCloud 0.14 still giving me problems

### ISSUE THREAD

**Issue by Krash-Bang** [cross-platform/icloud-for-linux#76]
Upgraded to 0.14 due to never ending stream of "Browser out of date errors" and am now getting "GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox" errors.

-Krash

**Comment by MarcusTomlinson** [comment]
Please try 0.15

**Comment by Krash-Bang** [comment]
Yep.  That did it.

-Krash
