### ISSUE TITLE
GDBus.Error:org.freedesktop.portal.Error.NotAllowed on initial launch

### ISSUE THREAD

**Issue by masonraus** [cross-platform/icloud-for-linux#77]
Encountering this error when attempting to open icloud Drive. Prior it was throwing a "Your browser is out of date" error but after updating to resolve this, now this error occurs

![image](https://github.com/cross-platform/icloud-for-linux/assets/4073048/850d9d45-ced8-4cf8-9584-fb49ae100674)

**Comment by MarcusTomlinson** [comment]
Please try 0.15
