### ISSUE TITLE
New error with build 0.16

### ISSUE THREAD

**Issue by pcoreyster** [cross-platform/icloud-for-linux#78]
As I was testing to confirm https://github.com/cross-platform/icloud-for-linux/issues/73 is fixed, I was not able to get "mail" to work.

I open my terminal to watch for more detail and here are my results:

/snap/bin/icloud-for-linux.mail 
Gtk-Message: 11:27:31.139: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:13340): Gtk-CRITICAL **: 11:27:31.192: gtk_window_resize: assertion 'width > 0' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

Initally I had snap just update the package from 0.14 to 0.16.  When mail was not launching, I remove my folder in home for icloud-for-linux.

I also remove the software, reboot, and reinstalled.

I was able to confirm the following apps are working (from the login screen to the final windows showing data):

- "drive" (icloud-for-linux.drive) 
- "calendar" (icloud-for-linux.calendar)
- "find" (icloud-for-linux.find)
- "keynote" (icloud-for-linux.keynote)
- "notes" (icloud-for-linux.notes)
- "numbers' (icloud-for-linux.numbers)
- "photos" (icloud-for-linux.photos)
- "reminders (icloud-for-linux.reminders)

mail does not reach to the step to show any dialog/window with a web login.

One item to note:  I also have all the detail for the 8 apps that are working (from a terminal window)

user@laptop:~$  icloud-for-linux.drive 
Gtk-Message: 11:44:50.815: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:17952): Gtk-CRITICAL **: 11:44:50.871: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:17952): WARNING **: 11:44:50.877: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:17952): WARNING **: 11:44:50.877: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:44:50.905: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:18041): WARNING **: 11:44:51.085: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:18041): WARNING **: 11:44:51.085: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:17952): GLib-GObject-WARNING **: 11:45:15.305: ../src/gobject/gsignal.c:2735: instance '0x62497ac11a50' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.contacts 
Gtk-Message: 11:36:07.684: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:15426): Gtk-CRITICAL **: 11:36:07.737: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:15426): WARNING **: 11:36:07.744: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:15426): WARNING **: 11:36:07.744: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:36:07.769: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:15510): WARNING **: 11:36:07.937: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:15510): WARNING **: 11:36:07.937: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:15426): GLib-GObject-WARNING **: 11:36:31.399: ../src/gobject/gsignal.c:2735: instance '0x5917a7a44050' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.calendar 
Gtk-Message: 11:36:50.870: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:15727): Gtk-CRITICAL **: 11:36:50.921: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:15727): WARNING **: 11:36:50.930: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:15727): WARNING **: 11:36:50.930: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:36:50.956: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:15816): WARNING **: 11:36:51.131: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:15816): WARNING **: 11:36:51.132: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:15727): GLib-GObject-WARNING **: 11:37:14.455: ../src/gobject/gsignal.c:2735: instance '0x6216abd02e50' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.find 
Gtk-Message: 11:37:20.371: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:16032): Gtk-CRITICAL **: 11:37:20.419: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:16032): WARNING **: 11:37:20.426: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:16032): WARNING **: 11:37:20.426: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:37:20.450: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:16119): WARNING **: 11:37:20.636: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:16119): WARNING **: 11:37:20.636: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:16032): GLib-GObject-WARNING **: 11:37:42.437: ../src/gobject/gsignal.c:2735: instance '0x5c1c06f41a50' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.keynote 
Gtk-Message: 11:37:49.776: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:16374): Gtk-CRITICAL **: 11:37:49.829: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:16374): WARNING **: 11:37:49.837: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:16374): WARNING **: 11:37:49.837: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:37:49.863: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:16461): WARNING **: 11:37:50.043: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:16461): WARNING **: 11:37:50.044: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:16374): GLib-GObject-WARNING **: 11:38:22.920: ../src/gobject/gsignal.c:2735: instance '0x5640f9cd4fc0' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.notes
Gtk-Message: 11:38:28.998: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:16702): Gtk-CRITICAL **: 11:38:29.049: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:16702): WARNING **: 11:38:29.056: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:16702): WARNING **: 11:38:29.056: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:38:29.080: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:16790): WARNING **: 11:38:29.248: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:16790): WARNING **: 11:38:29.248: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:16702): GLib-GObject-WARNING **: 11:38:50.932: ../src/gobject/gsignal.c:2735: instance '0x613521312c50' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.photos 
Gtk-Message: 11:38:57.281: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:17025): Gtk-CRITICAL **: 11:38:57.330: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:17025): WARNING **: 11:38:57.337: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:17025): WARNING **: 11:38:57.337: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:38:57.366: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:17109): WARNING **: 11:38:57.543: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:17109): WARNING **: 11:38:57.543: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:17025): GLib-GObject-WARNING **: 11:39:16.136: ../src/gobject/gsignal.c:2735: instance '0x56367245fc50' has no handler with id '150'

user@laptop:~$ /snap/bin/icloud-for-linux.reminders 
Gtk-Message: 11:39:22.693: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(icloud-for-linux:17338): Gtk-CRITICAL **: 11:39:22.744: gtk_window_resize: assertion 'width > 0' failed

** (icloud-for-linux:17338): WARNING **: 11:39:22.749: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (icloud-for-linux:17338): WARNING **: 11:39:22.749: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
Gtk-Message: 11:39:22.777: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (WebKitWebProcess:17427): WARNING **: 11:39:22.934: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied

** (WebKitWebProcess:17427): WARNING **: 11:39:22.934: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

(icloud-for-linux:17338): GLib-GObject-WARNING **: 11:39:41.621: ../src/gobject/gsignal.c:2735: instance '0x6064bfddc850' has no handler with id '150'

hope this details helps to find a resolution to why mail is not able to fully launch

**Comment by MarcusTomlinson** [comment]
Oh darn, sorry, mistake. This is now fixed in 0.17

**Comment by pcoreyster** [comment]
I was able to update the snap installation on my desktop/laptop.

The mail app works.

I will try to more testing to see if there any other issues.  I am assuming I will not find any.

If I can ask what was the extra item needed for mail to work vs the other apps.

**Comment by MarcusTomlinson** [comment]
> If I can ask what was the extra item needed for mail to work vs the other apps.

Silly mistake, I simply forgot the window title argument in the mail command-line: https://github.com/cross-platform/icloud-for-linux/commit/31089df93b8959be46c4b62f227677fec452c38c

**Comment by pcoreyster** [comment]
Thank you for the extra detail
