### ISSUE TITLE
Cannot drag files into the window to upload.

### ISSUE THREAD

**Issue by Xianqi-Zhang** [cross-platform/icloud-for-linux#79]
Hi,
Thanks for your work.

I want to report a **bug** about uploading files.
When dragging files into the window to upload, it shows that uploading folders to iCloud is not supported. 
However, when using the upload button, it works fine.

```
System: Ubuntu20.04
App: icloud-for-linux 0.19
iCloud: iCloud.com.cn
```

Best regards.

**Comment by davidil28** [comment]
I have the same issue 

- System Ubuntu 22.04 Jammy Jellyfish (x86-64) 
- Linux kernel 6.5.0-35-generic 
- App icloud-for-linux 0.19

**Comment by pcoreyster** [comment]
just to share my experience as I saw this issue.

I tested duplicate the issue using my existing system which tested  the past two issues I reported (https://github.com/cross-platform/icloud-for-linux/issues/78).

I tried to use drag/drop a file from Gnome Files to the web UI window launched by icloud-for-linux's iCloud Drive and iCloud Mail.

Both attempts worked without any issue.

I am using POP!_OS 22.04 which is using the latest updates/kernel -> 6.9.3-76060903-generic

Hope this help the developer

**Comment by MarcusTomlinson** [comment]
Please try the latest snap version, a fair bit has been fixed.

**Comment by M6700** [comment]
> Hi, Thanks for your work.
> 
> I want to report a **bug** about uploading files. When dragging files into the window to upload, it shows that uploading folders to iCloud is not supported. However, when using the upload button, it works fine.
> 
> ```
> System: Ubuntu20.04
> App: icloud-for-linux 0.19
> iCloud: iCloud.com.cn
> ```
> 
> Best regards.

I have the same issue, however, I cannot upload a folder, only files-neither drag or drop nor file upload will allow it.

Ubuntu Mate 22.04.4 Jammy Jellyfish
Latest version of iCloud for Linux

Thx

Chris

**Comment by MarcusTomlinson** [comment]
Ok yeah, chances are Apple don’t support this. Could you try going direct to iCloud.com in your browser and try it there
