### ISSUE TITLE
icloud photos - how to subscribe to shared album

### ISSUE THREAD

**Issue by azigit** [cross-platform/icloud-for-linux#8]
I've installed icloud-for-linux on a linux mint machine with the hope that I'd be able to accept an invitation to subscribe to a shared iCloud Photo album.
I've created an Apple ID but have no Apple devices.
When I launch iCloud Photos I get this message:
"Unable to load Photos - your apple id ### is not an iCloud account. Please sign in with the Apple ID from your device."
Can I access this shared album using icloud-for-linux?
Thanks for any help.

**Comment by MarcusTomlinson** [comment]
Could you try navigate to https://icloud.com/ in your browser and try signing in with your Apple ID there? It’s possible you may need to complete a registration process there before this app will work.

**Comment by azigit** [comment]
In firefox I cannot sign in at icloud.com.
In chrome I can sign in with my apple id. Icons for various services (Notes, Pages etc but not Photos or Albums) are then displayed. If I then open the email containing the invitation to subscribe to the album and click on Subscribe the following message is shown:
"iCloud Photo Sharing is not available for this device.
To subscribe to xxxxx shared album on your iPhone, iPad, iPod touch, or Mac, open your invitation in the Mail app, and click the Subscribe button in the message.
To subscribe you need to be signed in to iCloud on:
An iPhone, iPad, or iPod touch with iOS 6 or later, or
A Mac with macOS 10.8.2 or later and iPhoto 9.4 or Aperture 3.4 or later"
