### ISSUE TITLE
No Apps will open.

### ISSUE THREAD

**Issue by SethBasham** [cross-platform/icloud-for-linux#9]
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.4.24-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6300U CPU @ 2.40GHz
Memory: 15.4 GiB of RAM

----------

Anytime I attempt to open any of the apps, they show up in the taskbar for about 5 seconds and then disappear. No processes are showing up under HTOP. Uninstall iCloud-for-Linux and reinstalled and still the same results.

**Comment by MarcusTomlinson** [comment]
Could you try re-installing like this:

```
snap remove icloud-for-linux
rm -rf ~/snap/icloud-for-linux
snap install icloud-for-linux
```

If this still doesn't work, try `snap install icloud-for-linux --devmode` in place of the third step above.

**Comment by gberdzenishvili** [comment]
I got the same issue, running from terminal gives me the following:
```
"/home/george/iclouddrive" does not exist.
"/home/george/iCloud Drive" does not exist.
[10634:10634:0419/164123.719276:FATAL:credentials.cc(155)] Check failed: NamespaceUtils::DenySetgroups(). : Permission denied
#0 0x7f4232b97aee <unknown>
#1 0x7f4232baa0e2 <unknown>
#2 0x7f4232bab45c <unknown>
#3 0x7f423371fb21 <unknown>
#4 0x7f42337202dd <unknown>
#5 0x7f42327b4527 <unknown>
#6 0x7f423245fd48 <unknown>
#7 0x7f4232463262 <unknown>
#8 0x7f4232251a9b <unknown>
#9 0x7f4232252bd5 <unknown>
#10 0x7f42321e74f1 QtWebEngineCore::BrowserContextAdapter::defaultContext()
#11 0x7f423fbaf3b5 QQuickWebEngineProfile::defaultProfile()
#12 0x7f423fbb6dba QQuickWebEngineViewPrivate::QQuickWebEngineViewPrivate()
#13 0x7f423fbb7c9b QQuickWebEngineView::QQuickWebEngineView()
#14 0x7f423fdef27b <unknown>
#15 0x7f425b76f962 QQmlType::create()
#16 0x7f425b7e0146 QQmlObjectCreator::createInstance()
#17 0x7f425b7e23da QQmlObjectCreator::setPropertyBinding()
#18 0x7f425b7e2e11 QQmlObjectCreator::setupBindings()
#19 0x7f425b7dfba6 QQmlObjectCreator::populateInstance()
#20 0x7f425b7e097c QQmlObjectCreator::createInstance()
#21 0x7f425b7e3c6c QQmlObjectCreator::create()
#22 0x7f425b75a408 QQmlComponentPrivate::beginCreate()
#23 0x7f425b75874f QQmlComponent::create()
#24 0x559a14921c5a <unknown>
#25 0x7f4259318b97 __libc_start_main
#26 0x559a14923ada <unknown>

Fontconfig warning: FcPattern object weight does not accept value [50 200)
Segmentation fault (core dumped)
```

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
Kernel Version: 5.4.33-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.5 GiB of RAM

**Comment by MarcusTomlinson** [comment]
> I got the same issue, running from terminal gives me the following:
> 
> ```
> "/home/george/iclouddrive" does not exist.
> "/home/george/iCloud Drive" does not exist.
> [10634:10634:0419/164123.719276:FATAL:credentials.cc(155)] Check failed: NamespaceUtils::DenySetgroups(). : Permission denied
> #0 0x7f4232b97aee <unknown>
> #1 0x7f4232baa0e2 <unknown>
> #2 0x7f4232bab45c <unknown>
> #3 0x7f423371fb21 <unknown>
> #4 0x7f42337202dd <unknown>
> #5 0x7f42327b4527 <unknown>
> #6 0x7f423245fd48 <unknown>
> #7 0x7f4232463262 <unknown>
> #8 0x7f4232251a9b <unknown>
> #9 0x7f4232252bd5 <unknown>
> #10 0x7f42321e74f1 QtWebEngineCore::BrowserContextAdapter::defaultContext()
> #11 0x7f423fbaf3b5 QQuickWebEngineProfile::defaultProfile()
> #12 0x7f423fbb6dba QQuickWebEngineViewPrivate::QQuickWebEngineViewPrivate()
> #13 0x7f423fbb7c9b QQuickWebEngineView::QQuickWebEngineView()
> #14 0x7f423fdef27b <unknown>
> #15 0x7f425b76f962 QQmlType::create()
> #16 0x7f425b7e0146 QQmlObjectCreator::createInstance()
> #17 0x7f425b7e23da QQmlObjectCreator::setPropertyBinding()
> #18 0x7f425b7e2e11 QQmlObjectCreator::setupBindings()
> #19 0x7f425b7dfba6 QQmlObjectCreator::populateInstance()
> #20 0x7f425b7e097c QQmlObjectCreator::createInstance()
> #21 0x7f425b7e3c6c QQmlObjectCreator::create()
> #22 0x7f425b75a408 QQmlComponentPrivate::beginCreate()
> #23 0x7f425b75874f QQmlComponent::create()
> #24 0x559a14921c5a <unknown>
> #25 0x7f4259318b97 __libc_start_main
> #26 0x559a14923ada <unknown>
> 
> Fontconfig warning: FcPattern object weight does not accept value [50 200)
> Segmentation fault (core dumped)
> ```
> 
> Operating System: Manjaro Linux
> KDE Plasma Version: 5.18.4
> KDE Frameworks Version: 5.69.0
> Qt Version: 5.14.2
> Kernel Version: 5.4.33-1-MANJARO
> OS Type: 64-bit
> Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
> Memory: 15.5 GiB of RAM

Could you try:

sudo fc-cache -f -v

**Comment by yswtrue** [comment]
same issue. I have tried `sudo fc-cache -f -v`, and it won't work for me.

**Comment by yswtrue** [comment]
```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
These work for me.

**Comment by gberdzenishvili** [comment]
`sudo fc-cache -f -v` worked for me, thanks @MarcusTomlinson

**Comment by MarcusTomlinson** [comment]
@SethBasham, does clearing the font config cache work for you?

**Comment by MarcusTomlinson** [comment]
Duplicate of: https://github.com/cross-platform/icloud-for-linux/issues/17
