### ISSUE TITLE
Is there any way to install on Arch Linux without utilizing the snap store?

### ISSUE THREAD

**Issue by dultragab** [cross-platform/icloud-for-linux#91]
I was wondering if there's any way to install this package without utilizing the snap store on arch linux.
I really want to keep installed applications to a minimum on my distribution.

**Comment by Zachmd14** [comment]
Hello,
Did you find any solution ?

**Comment by dultragab** [comment]
> Hello,
> 
> Did you find any solution ?

Nah, just gave up. Started using the web version of iCloud instead.

**Comment by Zachmd14** [comment]
OK thank you,
I'm going to do the same thing.
