### ISSUE TITLE
Distribute on Flathub too?

### ISSUE THREAD

**Issue by Guillawme** [cross-platform/icloud-for-linux#92]
Hello,

This looks very helpful and I am wondering if you are also planning to distribute this software as a flatpak on [Flathub](https://flathub.org/)?
Thanks!

**Comment by titouan336** [comment]
i hope snapcraft is crap (snapcrap)

**Comment by MarcusTomlinson** [comment]
My intention for this project is for it to be a snap only. My suggestion, for anyone wanting to re-purpose this for other package managers, is to fork.

**Comment by upintheairsheep** [comment]
Anyone want to fork?

**Comment by titouan336** [comment]
i already tried but i really dont have the experience
